"""Import all models so SQLAlchemy metadata is fully populated (Alembic)."""

from app.db.base import Base
from app.models.assistant import AssistantConversation, AssistantMessage
from app.models.career import (
    AcademicGrade,
    CareerRecommendation,
    Consultation,
    PersonalityResult,
    ResourceItem,
    RoadmapMilestone,
)
from app.models.certificate import Certificate
from app.models.community import CommunityComment, CommunityLike, CommunityPost
from app.models.exam import (
    BP_SCALE,
    AttemptEvent,
    Exam,
    ExamAttempt,
    GradingJob,
    GradingResult,
    Question,
    QuestionOption,
    StudentAnswer,
)
from app.models.identity import (
    AuditLog,
    EmailChangeToken,
    PasswordResetToken,
    Role,
    Session,
    User,
    UserRole,
)
from app.models.learning import (
    Course,
    CourseMember,
    LearningMaterial,
    Lesson,
    LessonProgress,
    MaterialChunk,
)
from app.models.quest import (
    Quest,
    QuestAttempt,
    QuestRule,
    QuestWinner,
    Task,
    TaskCompletion,
)
from app.models.ranking import Leaderboard, LeaderboardEntry, RankingSnapshot
from app.models.room import Room, RoomEvent, RoomInvitation, RoomMember
from app.models.social import (
    Badge,
    Notification,
    NotificationPreference,
    UserBadge,
    UserProgress,
)
from app.models.wallet import (
    AiUsageCharge,
    BlockchainEvent,
    BlockchainTransaction,
    ContractDeployment,
    RewardAllocation,
    TransactionOutbox,
    WalletAccount,
    WalletAssetBalance,
    WalletLedgerEntry,
    WithdrawalRequest,
)

__all__ = [
    "Base",
    "BP_SCALE",
    "AttemptEvent",
    "AiUsageCharge",
    "User",
    "Role",
    "UserRole",
    "Session",
    "PasswordResetToken",
    "EmailChangeToken",
    "AuditLog",
    "Course",
    "CourseMember",
    "Lesson",
    "LearningMaterial",
    "LessonProgress",
    "MaterialChunk",
    "Room",
    "RoomMember",
    "RoomEvent",
    "RoomInvitation",
    "Exam",
    "Question",
    "QuestionOption",
    "ExamAttempt",
    "StudentAnswer",
    "GradingJob",
    "GradingResult",
    "Quest",
    "QuestRule",
    "QuestAttempt",
    "QuestWinner",
    "Task",
    "TaskCompletion",
    "Leaderboard",
    "LeaderboardEntry",
    "RankingSnapshot",
    "Notification",
    "Badge",
    "UserBadge",
    "UserProgress",
    "NotificationPreference",
    "AcademicGrade",
    "PersonalityResult",
    "CareerRecommendation",
    "RoadmapMilestone",
    "Consultation",
    "ResourceItem",
    "Certificate",
    "CommunityPost",
    "CommunityComment",
    "CommunityLike",
    "AssistantConversation",
    "AssistantMessage",
    "WalletAccount",
    "WalletAssetBalance",
    "WalletLedgerEntry",
    "RewardAllocation",
    "BlockchainTransaction",
    "BlockchainEvent",
    "ContractDeployment",
    "WithdrawalRequest",
    "TransactionOutbox",
]
