"""career guidance

Revision ID: 40fe9fda3870
Revises: da49ffdc90b9
Create Date: 2026-09-19 23:23:55.493394
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '40fe9fda3870'
down_revision: str | None = 'da49ffdc90b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_items')),
    sa.UniqueConstraint('code', name='uq_resource_items_code')
    )
    op.create_table('academic_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_academic_grades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_grades')),
    sa.UniqueConstraint('user_id', 'subject', 'term', name='uq_grade_user_subject_term')
    )
    op.create_index('ix_grades_user_term', 'academic_grades', ['user_id', 'term'], unique=False)
    op.create_table('career_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('academic_fit', sa.Integer(), nullable=False),
    sa.Column('personality_fit', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('universities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('admission_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('careers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_career_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_recommendations'))
    )
    op.create_index('ix_career_rec_user_created', 'career_recommendations', ['user_id', 'created_at'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('counselor', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consultations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index('ix_consultations_user_created', 'consultations', ['user_id', 'created_at'], unique=False)
    op.create_table('personality_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('openness', sa.Integer(), nullable=False),
    sa.Column('conscientiousness', sa.Integer(), nullable=False),
    sa.Column('extraversion', sa.Integer(), nullable=False),
    sa.Column('agreeableness', sa.Integer(), nullable=False),
    sa.Column('neuroticism', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personality_results_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personality_results'))
    )
    op.create_index(op.f('ix_personality_results_user_id'), 'personality_results', ['user_id'], unique=False)
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_roadmap_milestones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_milestones')),
    sa.UniqueConstraint('user_id', 'position', name='uq_milestone_user_position')
    )
    op.create_index(op.f('ix_roadmap_milestones_user_id'), 'roadmap_milestones', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_milestones_user_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    op.drop_index(op.f('ix_personality_results_user_id'), table_name='personality_results')
    op.drop_table('personality_results')
    op.drop_index('ix_consultations_user_created', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('ix_career_rec_user_created', table_name='career_recommendations')
    op.drop_table('career_recommendations')
    op.drop_index('ix_grades_user_term', table_name='academic_grades')
    op.drop_table('academic_grades')
    op.drop_table('resource_items')
    # ### end Alembic commands ###
