"""on-chain ids for courses and badges

Revision ID: 78b66b207e43
Revises: 8e79f835167b
Create Date: 2026-09-20 01:38:37.460436
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '78b66b207e43'
down_revision: str | None = '8e79f835167b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('on_chain_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_badges_on_chain_id'), 'badges', ['on_chain_id'])
    op.add_column('courses', sa.Column('on_chain_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_courses_on_chain_id'), 'courses', ['on_chain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_courses_on_chain_id'), 'courses', type_='unique')
    op.drop_column('courses', 'on_chain_id')
    op.drop_constraint(op.f('uq_badges_on_chain_id'), 'badges', type_='unique')
    op.drop_column('badges', 'on_chain_id')
    # ### end Alembic commands ###
