"""class-based subjects

Revision ID: 8e79f835167b
Revises: 40fe9fda3870
Create Date: 2026-09-20 00:59:11.491710
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e79f835167b'
down_revision: str | None = '40fe9fda3870'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class_code', sa.String(length=16), nullable=True))
    op.add_column('courses', sa.Column('class_type', sa.String(length=32), nullable=True))
    op.add_column('courses', sa.Column('subject', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_courses_class_code'), 'courses', ['class_code'], unique=False)
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.add_column('users', sa.Column('class_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('class_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_class_code'), 'users', ['class_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_class_code'), table_name='users')
    op.drop_column('users', 'class_type')
    op.drop_column('users', 'class_code')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_index(op.f('ix_courses_class_code'), table_name='courses')
    op.drop_column('courses', 'subject')
    op.drop_column('courses', 'class_type')
    op.drop_column('courses', 'class_code')
    # ### end Alembic commands ###
