"""certificates

Revision ID: a567874eb52c
Revises: a1c4b2e7f9d0
Create Date: 2026-09-21 08:04:17.712767
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a567874eb52c'
down_revision: str | None = 'a1c4b2e7f9d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(length=64), nullable=False),
    sa.Column('verification_hash', sa.String(length=64), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('edition_number', sa.Integer(), nullable=False),
    sa.Column('edition_total', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_certificates_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_certificates_credential_id')),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_certificates_user_course')
    )
    op.create_index('ix_certificates_user_issued', 'certificates', ['user_id', 'issued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certificates_user_issued', table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
