"""community feed

Revision ID: adc4a40c4dd5
Revises: a567874eb52c
Create Date: 2026-09-21 08:13:15.025600
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'adc4a40c4dd5'
down_revision: str | None = 'a567874eb52c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_community_posts_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_posts'))
    )
    op.create_index('ix_community_posts_created', 'community_posts', ['created_at'], unique=False)
    op.create_index('ix_community_posts_topic_created', 'community_posts', ['topic', 'created_at'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_community_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_community_comments_post_id_community_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_comments'))
    )
    op.create_index('ix_community_comments_post_created', 'community_comments', ['post_id', 'created_at'], unique=False)
    op.create_table('community_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_community_likes_post_id_community_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_community_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_likes')),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_community_likes_post_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_likes')
    op.drop_index('ix_community_comments_post_created', table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index('ix_community_posts_topic_created', table_name='community_posts')
    op.drop_index('ix_community_posts_created', table_name='community_posts')
    op.drop_table('community_posts')
    # ### end Alembic commands ###
